services:
  online-shop:
    image: online-shop:latest
    container_name: online-shop-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shop_db
      SPRING_DATASOURCE_USERNAME: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - db
    networks:
      - shop-network

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shop-network
    ports:
      - "5433:5432"

networks:
  shop-network:
    driver: bridge

volumes:
  pgdata: